runner_name: generation

data:
  data_dir: ./hf_data/release_v2406.json
  main_question_id: null

model:
  model_name: gemini   # gemini-1.5-pro
  use_api: true
  api_key: xx
  api_url: xx
  use_litellm_api: True

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024


