runner_name: generation

data:
  data_dir: ./hf_data/release_v2406.json
  question_id: null

model:
  model_name: custom_llm
  use_api: true
  api_key: xxx
  api_url: xxx
  model_full_name: xxx
  use_ocr: true
  is_reasoning_model: true
  
generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024