runner_name: generation

data:
  data_dir: ./hf_data/release_v2406.json
  question_id: null

model:
  model_name: custom_llm
  use_api: true
  api_key: e9085543-90fe-4502-b177-c5a034587d5e
  api_url: https://ark.cn-beijing.volces.com/api/v3
  model_full_name: ep-20250213112920-zldrb
  use_ocr: true
  is_reasoning_model: true
  
generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024