runner_name: generation

data:
  data_dir: ./hf_data/release_v2406.json
  main_question_id: null

model:
  model_name: custom_llm
  use_api: true
  api_key: xx
  api_url: https://ark.cn-beijing.volces.com/api/v3
  model_full_name: xx
  use_ocr: true

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024