runner_name: generation

data:
  data_dir: ./hf_data/release_v2501.json
  main_question_id: null

model:
  model_name: custom_llm
  model_full_name: custom_llm_full_name

generation:
  temperature: 1.0
  top_p: 0.9
  max_length: 1024


