config_cls_name: make_data 

data:
  source_csv_dir: ./source_data/FAMMA v1203 - merge.csv
  source_image_dir: /Users/siqiao/Downloads/

hf:
  repo_name: weaverbirdllm/famma
  version: release_v2406
  token: xx