config_cls_name: make_data 

data:
#  source_csv_dir: ./source_data/FAMMA v1203 - merge.csv
  source_csv_dir: [{version: release_v2501, path: './source_data/FAMMA Live - live_2501_v2.csv'},
  {version: release_v2406, path: './source_data/FAMMA v1203 - merge.csv'}]
#  source_csv_dir: [{version: release_v2501_ans, path: './source_data/FAMMA Live - live_2501_v2_ans.csv'}]
  source_image_dir: /Users/siqiao/Downloads/
  local_cache_dir: ./cache
  local_cache: False
hf:
  repo_name: weaverbirdllm/famma
  version: 2.0
  token: xx