runner_name: distillation

data:
  data_dir: ../hf_data/release_basic_txt.json # ./ddb_storage/Pro/deepseek-ai/DeepSeek-R1_distill_release_basic_txt.json  #  ../hf_data/release_basic_txt.json
  question_id: null
  rewrite_reasoning: false
  num_workers: 1

model:
  model_name: custom_llm # gpt4o # gemini claude_35_sonnet # gpt4o # gemini (gemini-1.5-pro) # claude_35_sonnet
  model_full_name: Pro/deepseek-ai/DeepSeek-R1 # DeepSeek-R1 # gemini-2.5-pro-002 # o1-mini # gemini-2.0-flash-thinking-exp-01-21 # o1-mini # gemini-2.0-flash-exp # gemini-2.0-flash-001 # gemini-2.0-pro-exp-02-05 # gemini-1.5-flash-002 # gemini-1.5-pro-002 # gpt-4o # gemini-2.0-flash-exp # vertex-sonnet-3.5 # gemini-1.5-pro-002
  use_api: true
  api_key: xx
  api_url: https://api.siliconflow.cn/v1 
  use_litellm_api: true

generation:
  temperature: 0.6
  top_p: 0.9
  max_length: 10240



