runner_name: evaluation

data:
  data_dir: ./ddb_storage/gemini-2.0-flash-exp_ans_release_v2501.json
  model_name_to_eval: gemini-2.0-flash-exp
  gold_dir: hf_data/release_v2501_ans.json
  main_question_id: None

model:
  model_name: gpt4o
  model_full_name: gpt-4o
  use_api: true
  api_key: xx
  api_url: https://litellm.vllm.yesy.dev
  use_litellm_api: True

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 518


