runner_name: evaluation

data:
  data_dir: ./ddb_storage/gpt4o_ans.json
  gold_dir: hf_data/release_v2406.json
  main_question_id: None

model:
  model_name: gpt4o
  use_api: true
  api_key: xx
  api_url: xx
  use_litellm_api: True

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 518


