runner_name: evaluation

data:
  data_dir: ./ddb_storage/o1-mini_ans_release_v2501
  model_name_to_eval: o1-mini
  gold_dir: hf_data/release_v2406.json
  question_id: None

model:
  model_name: gemini
  model_full_name: gemini-1.5-pro-002
  use_api: true
  api_key: xx
  api_url: https://litellm.vllm.yesy.dev
  use_litellm_api: True

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 518


