runner_name: generation

data:
  data_dir: ./hf_data/release_v2406.json
  main_question_id: null

model:
  model_name: qwen_vl  # by default, we use the qwen2-vl-72b-instruct model
  use_api: false
  model_dir: /workspaces/data/shoppal/siqiao/models--qwen2.5-vl-72b-instruct

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024


