runner_name: generation

data:
  data_dir: ./hf_data/release_v2406.json
  main_question_id: null

model:
  model_name: claude_35_sonnet # gpt4o # gemini (gemini-1.5-pro) # claude_35_sonnet
  model_full_name: vertex-sonnet-3.5
  use_api: true
  api_key: sk-VVPdjhNEpk5pEXA23x_wKA
  api_url: https://litellm.vllm.yesy.dev
  use_litellm_api: True

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024


