runner_name: generation

data:
  data_dir: ./hf_data/release_v2501.json
  question_id: null

model:
  model_name: qwen_vl  # by default, we use the qwen2-vl-72b-instruct model
  use_api: true
  api_key: xxx
  api_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model_full_name: qwen2.5-vl-72b-instruct
  use_ocr: false
  use_pot: false
  is_reasoning_model: false

generation:
  temperature: 0.0
  top_p: 0.9
  max_length: 1024


