runner_name: generation

data:
  data_dir: ./hf_data/release_v2501.json
  main_question_id: null

model:
  model_name: gemini # gemini claude_35_sonnet # gpt4o # gemini (gemini-1.5-pro) # claude_35_sonnet
  model_full_name: gemini-2.0-flash-exp # gemini-2.0-flash-001 # gemini-2.0-pro-exp-02-05 # gemini-1.5-flash-002 # gemini-1.5-pro-002 # gpt-4o # gemini-2.0-flash-exp # vertex-sonnet-3.5 # gemini-1.5-pro-002
  use_api: true
  api_key: xx
  api_url: https://litellm.vllm.yesy.dev
  use_litellm_api: True
  use_ocr: False

generation:
  temperature: 1.0
  top_p: 0.9
  max_length: 1024


